Repository apache/apisix, pull requests merged in 2020-11, with the labels that each got.

#2625 test: remove temporary hack
  .travis/linux_apisix_master_luarocks_runner.sh
  bin/apisix
Labels: CI

#2594 feat(jwt-auth): support to use of the RS256 algorithm
  apisix/plugins/jwt-auth.lua
  doc/plugins/jwt-auth.md
  doc/zh-cn/plugins/jwt-auth.md
  t/plugin/jwt-auth.t
Labels: plugin

#2615 docs: node-status.md
  doc/zh-cn/plugins/node-status.md
Labels: doc

#2684 feat(CI): create markdown-link-checker.yml
  .github/workflows/markdown-link-checker.yml
Labels: CI, enhancement

#2724 docs: modify batch-requests.md
  doc/plugins/batch-requests.md
  doc/zh-cn/plugins/batch-requests.md
Labels: doc

#2807 feat(kafka-logger): the key field should be optional.
  apisix/plugins/kafka-logger.lua
  doc/plugins/kafka-logger.md
  doc/zh-cn/plugins/kafka-logger.md
  t/plugin/kafka-logger.t
Labels: merge after release

#2811 feat: allow whitespace-wrapped variables in config.yaml
  .travis/apisix_cli_test.sh
  bin/apisix
Labels: merge after release

#2815 fix: check decrypt key to prevent lua thread aborted
  apisix/ssl/router/radixtree_sni.lua
  t/certs/incorrect.crt
  t/certs/incorrect.key
  t/router/radixtree-sni.t
Labels: merge after release

#2825 chore: remove stale access to modifiedIndex_org
  apisix/plugins/prometheus/exporter.lua
Labels: merge after release

#2844 docs: uses etcd to implement millisecond configuration sync
  FAQ_CN.md
Labels: doc
