Repository apache/apisix, pull requests merged in 2020-10, with the labels that each got.

#2421 feat:limit-count plugin supports consumer name field
  apisix/plugins/limit-count.lua
  doc/plugins/limit-count.md
  doc/zh-cn/plugins/limit-count.md
  t/plugin/limit-count.t
Labels: plugin

#2513 doc(AdminAPI): Correct the guide of creating consumer via POST method
  doc/admin-api.md
  doc/zh-cn/admin-api.md
Labels: doc

#2415 feat:The limit-conn plugin supports 'consumer_name' field
  apisix/plugins/limit-conn.lua
  doc/plugins/limit-conn.md
  doc/zh-cn/plugins/limit-conn.md
  t/plugin/limit-conn.t
Labels: plugin

#2539 feat(docs): update README
  README.md
  README_CN.md
Labels: doc

#2534 doc: add videos of ApacheCon.
  README.md
  README_CN.md
Labels: doc

#2458 [doc]to correct some typo and incorrect examples in getting-started.md and syslog.md
  doc/getting-started.md
  doc/plugins/syslog.md
  doc/zh-cn/getting-started.md
  doc/zh-cn/plugins/syslog.md
Labels: doc

#2225 move etcd cluster in docker for CI
  .github/workflows/build.yml
  .github/workflows/macOS.yml
  .travis/linux_apisix_current_luarocks_runner.sh
  .travis/linux_apisix_master_luarocks_runner.sh
  .travis/linux_openresty_mtls_runner.sh
  .travis/linux_openresty_runner.sh
  .travis/linux_tengine_runner.sh
  utils/linux-install-etcd-client.sh
Labels: waiting

#2524 CI : yaml style
  .github/workflows/build.yml
Labels: wait for update

#2525 doc : fixes issue #2327
  doc/README.md
  doc/zh-cn/README.md
Labels: wait for update
