Repository apache/apisix, pull requests merged in 2021-12, with the labels that each got.

#5734 feat: basic support OPA plugin
  Makefile
  apisix/core/request.lua
  apisix/plugins/opa.lua
  apisix/plugins/opa/helper.lua
  ci/linux-ci-init-service.sh
  ci/pod/docker-compose.yml
  conf/config-default.yaml
  t/admin/plugins.t
  t/core/request.t
  t/plugin/opa.t
Labels: enhancement

#5779 feat: supprot OPA plugin complex response
  apisix/plugins/opa.lua
  apisix/plugins/opa/helper.lua
  ci/linux-ci-init-service.sh
  ci/pod/docker-compose.yml
  ci/pod/opa/data.json
  ci/pod/opa/example.rego
  t/plugin/opa.t
Labels: enhancement

#5874 feat: support send APISIX data to assist decision in OPA plugin
  apisix/plugins/opa.lua
  apisix/plugins/opa/helper.lua
  ci/pod/docker-compose.yml
  ci/pod/opa/echo.rego
  t/plugin/opa2.t
Labels: enhancement, plugin

#5971 fix: upgrade skywalking to `0.6.0`
  rockspec/apisix-master-0.rockspec
Labels: need backport
