Repository apache/apisix, pull requests merged in 2022-01, with the labels that each got.

#5970 docs: add OPA plugin document
  docs/en/latest/config.json
  docs/en/latest/plugins/opa.md
Labels: plugin, doc

#6037 feat: add forward-auth plugin
  apisix/plugins/forward-auth.lua
  conf/config-default.yaml
  docs/en/latest/config.json
  docs/en/latest/plugins/forward-auth.md
  t/admin/plugins.t
  t/plugin/forward-auth.t
Labels: enhancement, plugin

#6155 fix(admin): correct the count field of plugin-metadata/global-rule
  apisix/admin/global_rules.lua
  apisix/admin/plugin_metadata.lua
  t/admin/global-rules2.t
  t/admin/plugin-metadata2.t
Labels: need backport

#6145 feat: add public api plugin
  apisix/init.lua
  apisix/plugins/public-api.lua
  conf/config-default.yaml
  t/admin/plugins.t
  t/plugin/plugin.t
  t/plugin/public-api.t
Labels: enhancement, plugin

#6204 fix(batch-requests): should be disabled by default
  conf/config-default.yaml
  t/admin/plugins.t
  t/debug/debug-mode.t
Labels: need backport

#6113 feat: development of Loggly logging plugin
  apisix/plugins/loggly.lua
  conf/config-default.yaml
  docs/assets/images/plugin/loggly-dashboard.png
  docs/en/latest/config.json
  docs/en/latest/plugins/loggly.md
  t/admin/plugins.t
  t/lib/mock_layer4.lua
  t/plugin/datadog.t
  t/plugin/loggly.t
Labels: enhancement

#6212 feat(loggly): support http/s bulk sending for batch logs
  apisix/plugins/loggly.lua
  docs/en/latest/plugins/loggly.md
  t/plugin/loggly.t
Labels: enhancement

#6160 fix(request-id): if the header_name is already present in the…
  apisix/plugins/request-id.lua
  t/plugin/request-id.t
Labels: need backport
