Repository apache/apisix, pull requests merged in 2022-08, with the labels that each got.

#7584 fix(redirect): compatible with old version data
  apisix/plugins/redirect.lua
  t/plugin/redirect.t
  t/plugin/redirect2.t
Labels: need backport

#7675 fix: remove the restriction of etcd prefix
  apisix/cli/schema.lua
  t/cli/test_validate_config.sh
Labels: need backport

#7750 fix(limit-count): different route with same conf should not share counter
  apisix/plugins/limit-count.lua
  t/plugin/limit-count3.t
Labels: need backport

#7240 feat: allow APISIX_PROFILE to be an empty string
  apisix/core/profile.lua
  t/core/profile.t
Labels: stale

#7778 feat: remove useless field in Admin API v3
  apisix/admin/consumers.lua
  apisix/admin/global_rules.lua
  apisix/admin/init.lua
  apisix/admin/plugin_config.lua
  apisix/admin/proto.lua
  apisix/admin/routes.lua
  apisix/admin/services.lua
  apisix/admin/ssl.lua
  apisix/admin/stream_routes.lua
  apisix/admin/upstreams.lua
  apisix/admin/v3_adapter.lua
  t/admin/consumers.t
  t/admin/consumers2.t
  t/admin/filter.t
  t/admin/global-rules.t
  t/admin/global-rules2.t
  t/admin/health-check.t
  t/admin/plugin-configs.t
  t/admin/response_body_format.t
  t/admin/routes-array-nodes.t
  t/admin/routes.t
  t/admin/routes2.t
  t/admin/routes3.t
  t/admin/routes4.t
  t/admin/services-array-nodes.t
  t/admin/services-string-id.t
  t/admin/services.t
  t/admin/services2.t
  t/admin/ssl.t
  t/admin/ssl2.t
  t/admin/ssl3.t
  t/admin/ssls.t
  t/admin/stream-routes.t
  t/admin/upstream-array-nodes.t
  t/admin/upstream.t
  t/admin/upstream2.t
  t/admin/upstream3.t
  t/admin/upstream4.t
  t/node/chash-hashon.t
  t/node/upstream-mtls.t
  t/plugin/echo.t
  t/plugin/google-cloud-logging2.t
  t/plugin/jwt-auth.t
  t/plugin/key-auth.t
  t/plugin/proxy-rewrite.t
  t/plugin/response-rewrite.t
  t/router/multi-ssl-certs.t
  t/router/radixtree-sni.t
  t/router/radixtree-sni2.t
  t/router/radixtree-uri-with-parameter.t
Labels: bug
