Repository apache/apisix, pull requests merged in 2022-02, with the labels that each got.

#6251 fix(batch-requests): real ip header should be overridden
  apisix/plugins/batch-requests.lua
  t/plugin/batch-requests2.t
Labels: need backport

#6242 fix(redirect-plugin): redirection loop behind a proxy or lb
  apisix/plugins/redirect.lua
  t/plugin/redirect.t
Labels: wait for update

#6136 ci: support for generating flame graph
  .github/workflows/build.yml
  .github/workflows/performance.yml
  ci/performance_test.sh
  t/perf/test_http.py
Labels: performance

#6379 fix: should not limit the header number
  apisix/core/request.lua
  apisix/plugins/request-validation.lua
  t/core/request.t
Labels: need backport

#6395 docs: fix configuration file typo
  docs/en/latest/config.json
  docs/zh/latest/config.json
Labels: bug, doc
