Repository apache/apisix, pull requests merged in 2023-12, with the labels that each got.

#10575 ci: new test case for https health check
  t/node/healthcheck-https.t
Labels: approved

#10404 refactor: add log after apisix.yml config reload in standalone mode
  apisix/core/config_yaml.lua
Labels: discuss

#10591 feat: add more attributes to `openid-connect` plugin
  apisix/plugins/openid-connect.lua
  docs/en/latest/plugins/openid-connect.md
  docs/zh/latest/plugins/openid-connect.md
  t/plugin/openid-connect.t
Labels: approved

#9365 feat(cors): support for the Timing-Allow-Origin header
  apisix/plugins/cors.lua
  docs/en/latest/plugins/cors.md
  t/plugin/cors4.t
Labels: enhancement, approved

#10515 feat: add brotli plugin
  .github/workflows/fuzzing-ci.yaml
  apisix-master-0.rockspec
  apisix/plugins/brotli.lua
  ci/centos7-ci.sh
  ci/common.sh
  ci/linux_apisix_current_luarocks_runner.sh
  ci/linux_apisix_master_luarocks_runner.sh
  ci/linux_openresty_common_runner.sh
  ci/redhat-ci.sh
  conf/config-default.yaml
  docs/en/latest/config.json
  docs/en/latest/plugins/brotli.md
  t/plugin/brotli.t
Labels: approved

#10612 feat: set minLength of redis_cluster_nodes to 1 for limit-count plugin
  apisix/plugins/limit-count.lua
  apisix/plugins/limit-count/init.lua
  t/plugin/limit-count-redis-cluster3.t
Labels: approved

#10619 fix: do not invoke add_header if value resolved as nil
  apisix/plugins/proxy-rewrite.lua
Labels: approved

#10632 docs: update the gzip plugin documentation
  docs/en/latest/plugins/gzip.md
  docs/zh/latest/plugins/gzip.md
Labels: approved

#10616 refactor: remove unused code and correct the docs for logger plugins
  apisix/plugins/clickhouse-logger.lua
  apisix/plugins/elasticsearch-logger.lua
  apisix/plugins/file-logger.lua
  apisix/plugins/google-cloud-logging.lua
  apisix/plugins/http-logger.lua
  apisix/plugins/kafka-logger.lua
  apisix/plugins/loki-logger.lua
  apisix/plugins/rocketmq-logger.lua
  apisix/plugins/skywalking-logger.lua
  apisix/plugins/splunk-hec-logging.lua
  apisix/plugins/syslog.lua
  apisix/plugins/tcp-logger.lua
  apisix/plugins/tencent-cloud-cls.lua
  apisix/plugins/udp-logger.lua
  apisix/stream/plugins/syslog.lua
  apisix/utils/log-util.lua
  docs/en/latest/plugins/clickhouse-logger.md
  docs/en/latest/plugins/elasticsearch-logger.md
  docs/en/latest/plugins/file-logger.md
  docs/en/latest/plugins/google-cloud-logging.md
  docs/en/latest/plugins/http-logger.md
  docs/en/latest/plugins/kafka-logger.md
  docs/en/latest/plugins/loki-logger.md
  docs/en/latest/plugins/rocketmq-logger.md
  docs/en/latest/plugins/skywalking-logger.md
  docs/en/latest/plugins/sls-logger.md
  docs/en/latest/plugins/splunk-hec-logging.md
  docs/en/latest/plugins/syslog.md
  docs/en/latest/plugins/tcp-logger.md
  docs/en/latest/plugins/tencent-cloud-cls.md
  docs/en/latest/plugins/udp-logger.md
  docs/zh/latest/plugins/clickhouse-logger.md
  docs/zh/latest/plugins/elasticsearch-logger.md
  docs/zh/latest/plugins/file-logger.md
  docs/zh/latest/plugins/google-cloud-logging.md
  docs/zh/latest/plugins/http-logger.md
  docs/zh/latest/plugins/kafka-logger.md
  docs/zh/latest/plugins/loki-logger.md
  docs/zh/latest/plugins/rocketmq-logger.md
  docs/zh/latest/plugins/skywalking-logger.md
  docs/zh/latest/plugins/sls-logger.md
  docs/zh/latest/plugins/splunk-hec-logging.md
  docs/zh/latest/plugins/syslog.md
  docs/zh/latest/plugins/tcp-logger.md
  docs/zh/latest/plugins/tencent-cloud-cls.md
  docs/zh/latest/plugins/udp-logger.md
Labels: approved

#9025 docs: update proxy-rewrite zh docs
  docs/zh/latest/plugins/proxy-rewrite.md
Labels: approved

#10607 feat: allow to use environment variables for limit-count plugin settings
  apisix/plugins/limit-count.lua
  docs/en/latest/plugins/limit-count.md
  t/plugin/limit-count-redis-cluster3.t
  t/plugin/limit-count-redis4.t
  t/plugin/limit-count5.t
Labels: approved

#10666 fix(zipkin): avoid getting a nil value in log phase(#10590)
  apisix/plugins/zipkin.lua
  t/plugin/zipkin.t
Labels: approved

#7690 fix(openid-connect): the default 'redirect_uri' (#2426)
  apisix/plugins/openid-connect.lua
  docs/en/latest/plugins/openid-connect.md
  docs/zh/latest/plugins/openid-connect.md
  t/plugin/openid-connect2.t
Labels: approved

#10695 docs: fix some errors in the pre-allocate table
  CODE_STYLE.md
Labels: approved

#10653 fix: add redirect_after_logout_uri for ODIC that do not have an end_session_endpoint
  apisix/plugins/openid-connect.lua
  docs/en/latest/plugins/openid-connect.md
  docs/zh/latest/plugins/openid-connect.md
  t/plugin/openid-connect.t
Labels: approved

#10637 fix: response-rewrite filters.regex does not apply when content-encoding is gzip
  apisix-master-0.rockspec
  apisix/plugins/response-rewrite.lua
  t/plugin/response-rewrite3.t
Labels: approved

#10655 fix: the leak of prometheus metrics
  apisix/plugins/prometheus/exporter.lua
  t/node/healthcheck-metric.t
Labels: approved

#10699 docs: update token endpoint command in `authz-keycloak` plugin doc
  docs/en/latest/plugins/authz-keycloak.md
  docs/zh/latest/plugins/authz-keycloak.md
Labels: approved

#10707 docs: use HTTP/1.1 201 Created
  docs/en/latest/getting-started/configure-routes.md
  docs/en/latest/getting-started/key-authentication.md
  docs/en/latest/getting-started/load-balancing.md
  docs/en/latest/getting-started/rate-limiting.md
  docs/zh/latest/getting-started/configure-routes.md
  docs/zh/latest/getting-started/key-authentication.md
  docs/zh/latest/getting-started/load-balancing.md
  docs/zh/latest/getting-started/rate-limiting.md
Labels: wait for update, user responded
