Repository apache/apisix, pull requests merged in 2023-06, with the labels that each got.

#9526 feat: Add real tests for splunk logger using vector
  ci/pod/docker-compose.plugin.yml
  ci/pod/vector/vector.toml
  t/plugin/splunk-hec-logging.t
Labels: approved

#9482 feat: Inform user when request /plugins/reload/ using wrong HTTP methods
  apisix/admin/init.lua
  t/admin/plugins-reload.t
Labels: approved

#9576 docs: updated Admin API wording for `HTTP Plugins`
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
Labels: approved

#9538 fix: replace mock tests with real tests in http logger
  ci/pod/docker-compose.plugin.yml
  ci/pod/vector/vector.toml
  t/plugin/http-logger-log-format.t
  t/plugin/udp-logger.t
Labels: approved

#9606 fix: save and restore pb state
  apisix/core/pubsub.lua
  apisix/plugins/grpc-transcode/proto.lua
  apisix/plugins/grpc-transcode/request.lua
  apisix/plugins/grpc-transcode/response.lua
  apisix/plugins/grpc-transcode/util.lua
  t/plugin/opentelemetry-bugfix-pb-state.t
Labels: approved

#9566 docs: correct behaviour of body_base64 field in docs
  docs/en/latest/plugins/response-rewrite.md
  docs/zh/latest/plugins/response-rewrite.md
Labels: approved

#9584 docs: adjust queries in Grafana dashboard
  docs/assets/other/json/apisix-grafana-dashboard.json
Labels: approved

#9602 docs: Update admin-api.md
  docs/zh/latest/admin-api.md
Labels: approved

#9646 docs: fix broken link
  docs/zh/latest/terminology/plugin.md
Labels: approved

#9574 refactor: return concise error when invalid resource is used
  apisix/admin/init.lua
  t/admin/resources.t
Labels: approved

#9665 docs: add missing triple backtick
  docs/en/latest/FAQ.md
Labels: approved

#9677 docs(loki-logger): fix content and format error
  docs/en/latest/plugins/loki-logger.md
Labels: doc, approved

#9680 docs: update Debian Installation Guide
  docs/en/latest/installation-guide.md
  docs/zh/latest/installation-guide.md
Labels: approved

#9684 docs: replace some urls that point to github with relative paths
  docs/en/latest/building-apisix.md
  docs/en/latest/discovery/kubernetes.md
  docs/en/latest/plugin-develop.md
  docs/en/latest/plugins/elasticsearch-logger.md
  docs/zh/latest/README.md
  docs/zh/latest/building-apisix.md
  docs/zh/latest/discovery/kubernetes.md
  docs/zh/latest/plugin-develop.md
  docs/zh/latest/plugins/elasticsearch-logger.md
Labels: checking

#9708 docs: add example for timeout
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
Labels: approved

#9673 feat(prometheus): allow user configure DEFAULT_BUCKETS
  apisix/plugins/prometheus/exporter.lua
  conf/config-default.yaml
  docs/en/latest/plugins/prometheus.md
  docs/zh/latest/plugins/prometheus.md
  t/plugin/prometheus4.t
Labels: approved

#9669 fix(body-transformer): xml2lua: replace empty table with empty string
  apisix/plugins/body-transformer.lua
  t/plugin/body-transformer.t
Labels: approved

#9635 fix: get the correct revision
  apisix/core/config_etcd.lua
Labels: approved

#9713 docs: add correct link for openresty arm64 repo
  docs/en/latest/installation-guide.md
Labels: approved

#9706 fix(ci): fix XDS test case
  t/xds-library/config_xds.t
Labels: approved

#9715 change(request-id): remove snowflake algorithm
  apisix/plugins/request-id.lua
  conf/config-default.yaml
  docs/en/latest/plugins/request-id.md
  docs/zh/latest/plugins/request-id.md
  rockspec/apisix-master-0.rockspec
  t/plugin/request-id-reload-bugfix.t
  t/plugin/request-id.t
Labels: approved

#9716 refactor(jwt-auth): remove unused parameter
  apisix/plugins/jwt-auth.lua
Labels: approved

#9662 chore: add missing `report_interval` option for `skywalking` plugin in `config-default.yaml`
  conf/config-default.yaml
Labels: approved

#9611 docs: update `apisix` section in `config-default.yaml`
  conf/config-default.yaml
Labels: approved

#9629 docs: explain in more details for the batch-requests plugin
  docs/en/latest/plugins/batch-requests.md
  docs/zh/latest/plugins/batch-requests.md
Labels: wait for update

#9749 fix(log-rotate): the max_kept configuration doesn't work when using custom name
  apisix/plugins/log-rotate.lua
  t/plugin/log-rotate3.t
Labels: approved
