Repository apache/apisix, pull requests merged in 2023-07, with the labels that each got.

#9522 docs: add Secret chinese document to Admin API
  docs/zh/latest/admin-api.md
Labels: approved

#9736 chore(update): replaced stand-alone with standalone
  README.md
  docs/en/latest/deployment-modes.md
  docs/en/latest/terminology/plugin.md
  docs/zh/latest/plugins/openwhisk.md
Labels: approved

#9687 docs: Chinese documentation for loki-logger
  docs/zh/latest/config.json
  docs/zh/latest/plugins/loki-logger.md
Labels: approved

#9765 docs: correct the wrong link in CHANGELOG.md
  CHANGELOG.md
  docs/zh/latest/CHANGELOG.md
Labels: approved

#9782 fix(workflow): enhance schema check
  apisix/plugins/workflow.lua
  t/plugin/workflow2.t
Labels: approved

#9658 docs: update remaining sections in `config-default.yaml`
  conf/config-default.yaml
Labels: approved

#9760 ci: check broken link
  .github/workflows/link-check.yml
  CHANGELOG.md
  README.md
  docs/en/latest/admin-api.md
  docs/en/latest/getting-started/configure-routes.md
  docs/en/latest/getting-started/key-authentication.md
  docs/en/latest/getting-started/load-balancing.md
  docs/en/latest/getting-started/rate-limiting.md
  docs/en/latest/plugin-develop.md
  docs/en/latest/plugins/authz-keycloak.md
  docs/en/latest/plugins/jwt-auth.md
  docs/en/latest/tutorials/health-check.md
  docs/en/latest/tutorials/protect-api.md
  docs/zh/latest/CHANGELOG.md
  docs/zh/latest/README.md
  docs/zh/latest/admin-api.md
  docs/zh/latest/getting-started.md
  docs/zh/latest/plugins/authz-keycloak.md
  docs/zh/latest/plugins/dubbo-proxy.md
  docs/zh/latest/plugins/elasticsearch-logger.md
  docs/zh/latest/plugins/jwt-auth.md
  docs/zh/latest/plugins/zipkin.md
  docs/zh/latest/tutorials/expose-api.md
  docs/zh/latest/tutorials/protect-api.md
  powered-by.md
Labels: approved

#9799 docs: fix typo in pubsub.md
  docs/en/latest/pubsub.md
Labels: approved

#9815 docs: add information to better explain plugin execution priorities and precedences
  docs/en/latest/terminology/plugin.md
  docs/zh/latest/terminology/plugin.md
Labels: approved

#9816 fix(limit_conn): do not use the http variable in stream mode
  apisix/plugins/limit-conn/init.lua
  t/stream-plugin/limit-conn2.t
Labels: approved

#9607 change: refactor logic for enabling L4/L7 proxy
  apisix/admin/init.lua
  apisix/cli/ngx_tpl.lua
  apisix/cli/ops.lua
  apisix/cli/schema.lua
  conf/config-default.yaml
  docs/en/latest/plugins/mqtt-proxy.md
  docs/en/latest/stream-proxy.md
  docs/zh/latest/plugins/mqtt-proxy.md
  docs/zh/latest/stream-proxy.md
  t/APISIX.pm
  t/cli/test_access_log.sh
  t/cli/test_core_config.sh
  t/cli/test_deployment_traditional.sh
  t/cli/test_dns.sh
  t/cli/test_etcd_grpc_mtls.sh
  t/cli/test_etcd_mtls.sh
  t/cli/test_main.sh
  t/cli/test_prometheus_run_in_privileged.sh
  t/cli/test_prometheus_stream.sh
  t/cli/test_snippet.sh
  t/cli/test_stream_config.sh
  t/cli/test_tls_over_tcp.sh
  t/cli/test_validate_config.sh
  t/stream-node/sni.t
Labels: approved

#9712 feat: file-logger add vars
  apisix/plugins/file-logger.lua
  apisix/utils/log-util.lua
  docs/en/latest/plugins/file-logger.md
  docs/zh/latest/plugins/file-logger.md
  t/plugin/file-logger2.t
Labels: approved

#9784 refactor: move global_rules to separate file
  apisix/admin/upstreams.lua
  apisix/global_rules.lua
  apisix/init.lua
  apisix/plugin.lua
  apisix/plugins/ai.lua
  apisix/plugins/prometheus/exporter.lua
  apisix/router.lua
  t/admin/upstream5.t
Labels: approved

#9720 feat: mock plugin support adding headers
  apisix/plugins/mocking.lua
  docs/en/latest/plugins/mocking.md
  docs/zh/latest/plugins/mocking.md
  t/plugin/mocking.t
Labels: approved

#9811 fix: update_count is reset once updated, cause cache key conflict
  apisix/plugin_config.lua
  apisix/router.lua
  docs/en/latest/control-api.md
  t/config-center-yaml/plugin-configs.t
  t/node/plugin-configs.t
Labels: need backport, approved

#9813 fix: support regex_uri with unsafe_uri in proxy-rewrite
  apisix/plugins/proxy-rewrite.lua
  t/plugin/proxy-rewrite3.t
Labels: approved

#9810 feat: support force delete resource
  apisix/admin/proto.lua
  apisix/admin/resource.lua
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
  t/admin/consumer-group-force-delete.t
  t/admin/plugin-configs-force-delete.t
  t/admin/protos-force-delete.t
  t/admin/services-force-delete.t
  t/admin/upstream-force-delete.t
Labels: approved

#9833 docs: fix typo
  docs/en/latest/debug-mode.md
Labels: approved

#9845 fix(ci): regex does not match err.log for xrpc
  t/xrpc/redis2.t
Labels: approved

#9837 fix: upgrade api7-lua-resty-jwt to 0.2.5
  rockspec/apisix-master-0.rockspec
Labels: approved

#9622 fix(google-cloud-logging): add missing config
  apisix/plugins/google-cloud-logging.lua
  docs/en/latest/plugins/google-cloud-logging.md
  docs/zh/latest/plugins/google-cloud-logging.md
  t/plugin/google-cloud-logging.t
  t/plugin/google-cloud-logging2.t
Labels: approved

#9580 change: Improve results from admin API while GET all plugins
  apisix/admin/init.lua
  apisix/admin/plugins.lua
  apisix/plugin.lua
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
  t/admin/plugins.t
  t/admin/schema.t
Labels: approved

#9081 docs: using curl silent mod when fetching version
  docs/en/latest/getting-started.md
Labels: approved

#9710 feat: allow sending headers upstream returned by OPA server
  apisix/plugins/opa.lua
  ci/pod/opa/example.rego
  t/plugin/opa.t
Labels: approved

#9778 refactor(consumer-restriction): optimize the error log when the corresponding resource is not fetched
  apisix/plugins/consumer-restriction.lua
  t/plugin/consumer-restriction.t
  t/plugin/consumer-restriction2.t
Labels: approved

#9846 refactor: access customized config directly
  apisix/cli/file.lua
  apisix/cli/ops.lua
  apisix/cli/util.lua
  apisix/core/profile.lua
  t/cli/test_cmd.sh
Labels: approved

#9850 fix: loki-logger nil context in batch processor
  apisix/plugins/loki-logger.lua
  t/plugin/loki-logger.t
Labels: approved

#9841 change(ua-restriction): allowlist and denylist can't be enabled at the same time
  apisix/plugins/ua-restriction.lua
  docs/en/latest/plugins/ua-restriction.md
  docs/zh/latest/plugins/ua-restriction.md
  t/plugin/ua-restriction.t
Labels: approved

#9886 docs: fix displaying code block
  docs/zh/latest/terminology/upstream.md
Labels: approved

#9897 docs: Add tutorial on monitoring API health check
  docs/en/latest/config.json
  docs/en/latest/tutorials/monitor-api-health-check.md
Labels: approved

#9902 docs: add example for protos
  docs/en/latest/deployment-modes.md
Labels: wait for update

#9906 perf(ssl): break out right after sni matched.
  apisix/ssl/router/radixtree_sni.lua
Labels: approved

#9919 fix: avoid using nightly version of openwhisk
  ci/init-plugin-test-service.sh
Labels: approved
