Repository apache/apisix, pull requests merged in 2023-08, with the labels that each got.

#9958 fix(ci): expired certificates of ldap
  t/certs/localhost_slapd_cert.pem
  t/certs/localhost_slapd_key.pem
  t/plugin/ldap-auth.t
Labels: approved

#9947 fix: add default value for range_id object
  apisix/plugins/request-id.lua
  t/plugin/request-id2.t
Labels: approved

#9952 build(luarocks): the option --tree and --local are mutually exclusive
  Makefile
Labels: approved

#9903 feat: support host level dynamic setting of tls protocol version
  apisix/cli/ngx_tpl.lua
  apisix/init.lua
  apisix/schema_def.lua
  apisix/ssl.lua
  apisix/ssl/router/radixtree_sni.lua
  ci/common.sh
  ci/linux-install-openresty.sh
  docs/en/latest/admin-api.md
  docs/en/latest/config.json
  docs/en/latest/ssl-protocol.md
  docs/zh/latest/admin-api.md
  docs/zh/latest/config.json
  docs/zh/latest/ssl-protocol.md
  t/APISIX.pm
  t/admin/ssl5.t
  t/node/ssl-protocols.t
  t/router/radixtree-sni.t
  t/router/radixtree-sni2.t
Labels: approved

#9966 fix: update penlight to 1.13.1
  rockspec/apisix-master-0.rockspec
Labels: approved

#9855 feat: support pulling env vars from yaml keys
  apisix/cli/file.lua
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
  t/cli/test_standalone.sh
Labels: approved

#9926 chore: remove check of OpenResty in code because APISIX can not start when using an old version of OpenResty
  apisix/discovery/kubernetes/init.lua
  apisix/discovery/tars/init.lua
  docs/en/latest/discovery/kubernetes.md
  docs/zh/latest/discovery/kubernetes.md
Labels: approved

#9969 docs: add in-memory caching example for `proxy-cache`
  docs/en/latest/plugins/proxy-cache.md
  docs/zh/latest/plugins/proxy-cache.md
Labels: approved

#9978 fix(limit-count): X-RateLimit-Reset shouldn't be set to 0 after request be rejected
  apisix/plugins/limit-count/limit-count-local.lua
  t/plugin/limit-count-redis-cluster2.t
  t/plugin/limit-count-redis3.t
  t/plugin/limit-count4.t
Labels: approved

#9971 docs: add more details for consumer-restriction plugin
  docs/en/latest/plugins/consumer-restriction.md
  docs/zh/latest/plugins/consumer-restriction.md
Labels: approved

#9960 fix(nacos): add skipped nil check for "applications" upvalue
  apisix/discovery/nacos/init.lua
Labels: approved

#9927 chore(ci): automate management of unresponded issues
  .github/workflows/close-unresponded.yml
  .github/workflows/update-labels.yml
Labels: approved

#9985 fix: add support for dependency installation on endeavouros
  utils/install-dependencies.sh
Labels: approved

#9944 perf(aws-lambda): cache the index of the array
  apisix/plugins/aws-lambda.lua
Labels: approved

#9967 fix: can't sync etcd data if key has special character
  apisix/core/config_etcd.lua
  t/core/config_etcd.t
Labels: approved

#9984 perf(log-rotate): replace string.sub with string.byte
  apisix/plugins/log-rotate.lua
Labels: approved

#9948 feat(openid-connect): add proxy_opts attribute
  apisix/plugins/openid-connect.lua
  docs/en/latest/plugins/openid-connect.md
  docs/zh/latest/plugins/openid-connect.md
  t/plugin/openid-connect3.t
Labels: approved

#9843 fix(tencent-cloud-cls): DNS parsing failure
  apisix/plugins/tencent-cloud-cls/cls-sdk.lua
  t/plugin/tencent-cloud-cls.t
Labels: approved

#10026 ci: update the timeout value in cli.yml
  .github/workflows/cli.yml
Labels: approved

#10008 fix: traffic split plugin not validating upstream_id
  apisix/plugins/traffic-split.lua
  t/plugin/traffic-split2.t
Labels: approved

#9909 fix: worker not exited when executing quit or reload command
  apisix/core/config_etcd.lua
  t/cli/test_cmd.sh
  t/node/healthcheck-stop-checker.t
Labels: approved

#10065 feat: add schema validate admin API
  apisix/admin/init.lua
  docs/en/latest/admin-api.md
  t/admin/schema-validate.t
Labels: approved

#10021 docs: mention how to use environment variables in configuration file
  docs/en/latest/profile.md
Labels: wait for update

#10075 docs(ssl-protocol): fix chinese doc
  docs/zh/latest/ssl-protocol.md
Labels: wait for update

#10083 docs: clarify meaning of "weight" in nacos
  conf/config-default.yaml
  docs/en/latest/discovery/nacos.md
Labels: doc

#10072 feat: support pass json to wasm plugin
  apisix/wasm.lua
  t/wasm/fault-injection.t
  t/wasm/request-body.t
  t/wasm/route.t
Labels: wait for update

#9050 docs: add missing Admin API Plugin endpoints
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
Labels: doc
