Repository apache/apisix, pull requests merged in 2023-10, with the labels that each got.

#10232 change: creating core resources does not allow passing in `create_time` and `update_time`
  apisix/admin/resource.lua
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
  t/admin/consumers.t
  t/admin/routes4.t
  t/admin/services.t
  t/admin/ssl.t
  t/admin/upstream4.t
Labels: approved

#10278 feat: add token support for consul discovery (#9532)
  apisix/discovery/consul/init.lua
  apisix/discovery/consul/schema.lua
  apisix/discovery/consul_kv/init.lua
  apisix/discovery/consul_kv/schema.lua
  ci/pod/docker-compose.first.yml
  docs/en/latest/discovery/consul.md
  docs/en/latest/discovery/consul_kv.md
  t/control/discovery.t
  t/discovery/consul.t
  t/discovery/consul_kv.t
Labels: wait for update, user responded

#10156 fix: use warn log for get healthcheck target status failure
  apisix/balancer.lua
Labels: approved

#10314 fix: update schema description in cors.lua
  apisix/plugins/cors.lua
Labels: approved

#10313 docs: update example in `cors` plugin for v3.6.0
  apisix/plugins/cors.lua
  docs/en/latest/plugins/cors.md
  docs/zh/latest/plugins/cors.md
  t/plugin/cors.t
  t/plugin/cors2.t
Labels: approved

#10269 fix: fix and optimize tls in upstream_schema
  apisix/schema_def.lua
  t/core/schema_def.t
Labels: bug, approved

#8867 docs: update Upstream`s Request Body Parameters add lost Type colum a…
  docs/en/latest/admin-api.md
Labels: wait for update

#10298 feat: support config stream_route upstream in service
  apisix/admin/services.lua
  apisix/admin/stream_routes.lua
  apisix/constants.lua
  apisix/http/service.lua
  apisix/init.lua
  apisix/plugin.lua
  apisix/schema_def.lua
  apisix/stream/router/ip_port.lua
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
  t/stream-node/sanity-with-service.t
Labels: wait for update

#10354 chore: update rules for unresponded issues
  .github/workflows/close-unresponded.yml
Labels: approved

#10058 feat: Add authorization params to openid-connect plugin
  apisix/plugins/openid-connect.lua
  docs/en/latest/plugins/openid-connect.md
  docs/zh/latest/plugins/openid-connect.md
  t/plugin/openid-connect4.t
Labels: approved

#8777 test(clickhouse-logger): to show that different endpoints will be chosen randomly
  t/plugin/clickhouse-logger.t
Labels: approved

#10361 feat: add zipkin variable
  apisix/cli/ngx_tpl.lua
  apisix/cli/ops.lua
  apisix/plugins/zipkin.lua
  conf/config-default.yaml
  docs/en/latest/plugins/zipkin.md
  docs/zh/latest/plugins/zipkin.md
  t/cli/test_zipkin_set_ngx_var.sh
  t/plugin/zipkin3.t
Labels: approved

#10403 fix: make install failed on mac
  Makefile
Labels: approved
