Repository apache/apisix, pull requests merged in 2024-01, with the labels that each got.

#10738 feat: Add schema attribute definition for some log plug-ins
  apisix/plugins/file-logger.lua
  apisix/plugins/http-logger.lua
  apisix/plugins/loggly.lua
  apisix/plugins/tencent-cloud-cls.lua
  docs/en/latest/plugins/file-logger.md
  docs/en/latest/plugins/http-logger.md
  docs/en/latest/plugins/loggly.md
  docs/en/latest/plugins/tencent-cloud-cls.md
  docs/zh/latest/plugins/file-logger.md
  docs/zh/latest/plugins/http-logger.md
  t/plugin/file-logger2.t
  t/plugin/http-logger-json.t
  t/plugin/loggly.t
  t/plugin/tencent-cloud-cls.t
Labels: approved

#10729 fix: install apisix-runtime when install APISIX from source
  .github/workflows/source-install.yml
  .requirements
  Makefile
  ci/centos7-ci.sh
  ci/linux-install-openresty.sh
  ci/redhat-ci.sh
  docs/en/latest/building-apisix.md
  docs/zh/latest/building-apisix.md
  utils/install-dependencies.sh
Labels: wait for update

#10696 fix: apisix restart failed (#10495)
  apisix/cli/ops.lua
  t/cli/test_cmd.sh
  t/cli/test_validate_config.sh
Labels: approved

#10733 feat(response-rewrite): support brotli when use filters.regex option
  apisix/plugins/response-rewrite.lua
  t/plugin/response-rewrite3.t
Labels: wait for update, user responded

#10763 fix: authz_keycloak plugin giving 500 error
  apisix/plugins/authz-keycloak.lua
  t/plugin/authz-keycloak2.t
Labels: approved

#10670 fix(openid-connect): use_jwks breaking authentication header
  apisix/plugins/openid-connect.lua
  t/plugin/openid-connect.t
Labels: approved

#10777 docs: update plugin-config.md
  docs/en/latest/terminology/plugin-config.md
Labels: approved

#10755 docs: add info about env var usage
  docs/en/latest/deployment-modes.md
  docs/en/latest/profile.md
Labels: wait for update

#10764 docs: Add default log format for each logger plugin
  docs/en/latest/plugins/clickhouse-logger.md
  docs/en/latest/plugins/elasticsearch-logger.md
  docs/en/latest/plugins/error-log-logger.md
  docs/en/latest/plugins/file-logger.md
  docs/en/latest/plugins/google-cloud-logging.md
  docs/en/latest/plugins/http-logger.md
  docs/en/latest/plugins/loggly.md
  docs/en/latest/plugins/loki-logger.md
  docs/en/latest/plugins/rocketmq-logger.md
  docs/en/latest/plugins/skywalking-logger.md
  docs/en/latest/plugins/sls-logger.md
  docs/en/latest/plugins/splunk-hec-logging.md
  docs/en/latest/plugins/syslog.md
  docs/en/latest/plugins/tcp-logger.md
  docs/en/latest/plugins/tencent-cloud-cls.md
  docs/en/latest/plugins/udp-logger.md
  docs/zh/latest/plugins/clickhouse-logger.md
  docs/zh/latest/plugins/elasticsearch-logger.md
  docs/zh/latest/plugins/error-log-logger.md
  docs/zh/latest/plugins/file-logger.md
  docs/zh/latest/plugins/google-cloud-logging.md
  docs/zh/latest/plugins/http-logger.md
  docs/zh/latest/plugins/loggly.md
  docs/zh/latest/plugins/loki-logger.md
  docs/zh/latest/plugins/rocketmq-logger.md
  docs/zh/latest/plugins/skywalking-logger.md
  docs/zh/latest/plugins/sls-logger.md
  docs/zh/latest/plugins/splunk-hec-logging.md
  docs/zh/latest/plugins/syslog.md
  docs/zh/latest/plugins/tcp-logger.md
  docs/zh/latest/plugins/tencent-cloud-cls.md
  docs/zh/latest/plugins/udp-logger.md
Labels: approved

#10790 docs: fix request url error in certificate doc
  docs/en/latest/certificate.md
Labels: approved

#10773 docs: use shell instead of python to configure ssls resources
  docs/en/latest/mtls.md
  docs/zh/latest/mtls.md
Labels: approved

#9065 fix: unnecessary YAML Config reloads
  apisix/core/config_yaml.lua
  t/cli/test_standalone.sh
Labels: approved

#10645 feat: Provide `uri_arg_` when `radixtree_uri_with_parameter`
  apisix/core/ctx.lua
  t/core/ctx_with_params.t
Labels: approved

#10740 fix(brotli-plugin): Skip brotli compression for upstream compressed response
  apisix/plugins/brotli.lua
  docs/en/latest/plugins/brotli.md
  t/lib/server.lua
  t/plugin/brotli.t
Labels: approved

#10820 chore: update installation-guide doc
  docs/en/latest/installation-guide.md
  docs/zh/latest/installation-guide.md
Labels: need backport

#10813 fix: linux-install-luarocks are not compatible with the openresty env…
  utils/linux-install-luarocks.sh
Labels: approved

#10816 docs: update `jwe-decrypt` plugin info
  docs/en/latest/plugins/jwe-decrypt.md
  docs/zh/latest/plugins/jwe-decrypt.md
Labels: approved

#10788 fix(openid-connect): openid not closing session and blocking until ttl…
  apisix/plugins/openid-connect.lua
  t/plugin/openid-connect5.t
Labels: approved

#10817 feat: add ocsp-stapling plugin
  .licenserc.yaml
  apisix/cli/ngx_tpl.lua
  apisix/init.lua
  apisix/plugins/ocsp-stapling.lua
  apisix/ssl.lua
  apisix/ssl/router/radixtree_sni.lua
  conf/config-default.yaml
  t/APISIX.pm
  t/certs/ocsp/ecc_good.crt
  t/certs/ocsp/ecc_good.key
  t/certs/ocsp/index.txt
  t/certs/ocsp/rsa_good.crt
  t/certs/ocsp/rsa_good.key
  t/certs/ocsp/rsa_revoked.crt
  t/certs/ocsp/rsa_revoked.key
  t/certs/ocsp/rsa_unknown.crt
  t/certs/ocsp/rsa_unknown.key
  t/certs/ocsp/signer.crt
  t/certs/ocsp/signer.key
  t/plugin/ocsp-stapling.t
Labels: wait for update, user responded

#10771 change: unify the keyring and key_encrypt_salt fields, remove ssl:key_encrypt_salt
  apisix/cli/file.lua
  apisix/cli/schema.lua
  apisix/plugin.lua
  apisix/ssl.lua
  conf/config-default.yaml
  t/admin/ssl2.t
  t/admin/ssl4.t
  t/node/data_encrypt.t
  t/node/data_encrypt2.t
  t/node/upstream-mtls.t
  t/plugin/authz-casdoor.t
  t/plugin/authz-keycloak3.t
  t/plugin/csrf.t
  t/plugin/elasticsearch-logger.t
  t/plugin/error-log-logger-clickhouse.t
  t/plugin/google-cloud-logging2.t
  t/plugin/hmac-auth3.t
  t/plugin/jwt-auth3.t
  t/plugin/kafka-proxy.t
  t/plugin/openid-connect2.t
  t/plugin/rocketmq-logger2.t
  t/plugin/sls-logger.t
  t/plugin/tencent-cloud-cls.t
Labels: approved

#10872 feat: support built-in variables in response_headers in mocking plugin
  apisix/plugins/mocking.lua
  t/plugin/mocking.t
Labels: approved
