Repository apache/apisix, pull requests merged in 2024-09, with the labels that each got.

#11550 docs: correct rate in `limit-req` plugin example
  docs/en/latest/plugins/limit-req.md
  docs/zh/latest/plugins/limit-req.md
Labels: plugin, doc, wait for update, user responded, size:S

#11552 chore: add `http.lua_shared_dict.prometheus-metrics` annotation in `config.yaml.example` file
  conf/config.yaml.example
Labels: doc, size:XS

#11570 fix(ci): foo.com is no longer a bad gateway
  t/plugin/traffic-split3.t
Labels: CI, size:XS

#11545 fix: confusion when substituting ENV in config file
  apisix/cli/ops.lua
  t/cli/cli_envsubst_confusion.t
  t/cli/test_main.sh
  t/cli/test_standalone.sh
Labels: bug, size:L

#11508 style(multi-auth): code formate
  apisix/plugins/multi-auth.lua
Labels: plugin, size:XS

#11499 feat: ai-proxy plugin
  Makefile
  apisix/cli/config.lua
  apisix/core/request.lua
  apisix/plugins/ai-proxy.lua
  apisix/plugins/ai-proxy/drivers/openai.lua
  apisix/plugins/ai-proxy/schema.lua
  ci/common.sh
  ci/linux_openresty_common_runner.sh
  ci/redhat-ci.sh
  conf/config.yaml.example
  docs/en/latest/config.json
  docs/en/latest/plugins/ai-proxy.md
  t/admin/plugins.t
  t/assets/ai-proxy-response.json
  t/plugin/ai-proxy.t
  t/plugin/ai-proxy2.t
  t/sse_server_example/go.mod
  t/sse_server_example/main.go
Labels: enhancement, plugin, size:XXL

#11581 feat: rewrite hmac-auth plugin for usability
  apisix/plugins/hmac-auth.lua
  t/node/consumer-plugin.t
  t/plugin/consumer-restriction.t
  t/plugin/hmac-auth-custom.t
  t/plugin/hmac-auth.t
  t/plugin/hmac-auth2.t
  t/plugin/hmac-auth3.t
  t/plugin/hmac-auth4.t
Labels: plugin, size:XXL

#11436 feat: support gcp secret manager
  apisix/secret/gcp.lua
  apisix/utils/google-cloud-oauth.lua
  docs/en/latest/terminology/secret.md
  docs/zh/latest/terminology/secret.md
  t/lib/server.lua
  t/secret/conf/error.json
  t/secret/conf/success.json
  t/secret/gcp.t
Labels: size:XXL

#11600 fix: encryption/decryption for non-auth plugins in consumer
  apisix/plugin.lua
  t/node/consumer-plugin3.t
Labels: bug, size:L

#11601 feat: implement credential
  apisix/admin/consumers.lua
  apisix/admin/credentials.lua
  apisix/admin/init.lua
  apisix/admin/resource.lua
  apisix/consumer.lua
  apisix/core/config_etcd.lua
  apisix/core/etcd.lua
  apisix/schema_def.lua
  docs/en/latest/admin-api.md
  docs/en/latest/config.json
  docs/en/latest/terminology/credential.md
  docs/zh/latest/admin-api.md
  docs/zh/latest/config.json
  docs/zh/latest/terminology/credential.md
  t/admin/credentials.t
  t/node/consumer-plugin.t
  t/node/consumer-plugin2.t
  t/node/credential-plugin-basic-auth.t
  t/node/credential-plugin-incremental-effective.t
  t/node/credential-plugin-jwt-auth.t
  t/node/credential-plugin-key-auth.t
  t/node/credential-plugin-multi-credentials.t
  t/node/credential-plugin-set-request-header.t
  t/node/credential-plugin-work-with-other-plugin.t
Labels: enhancement, size:XXL

#11603 chore: upgrade `skywalking-nginx-lua` version
  apisix-master-0.rockspec
Labels: dependencies, chore, size:XS

#11610 ci: remove useless ci and tests
  .github/workflows/performance.yml
  .licenserc.yaml
  ci/performance_test.sh
  t/fips/jwt-auth.t
  t/fips/openid-connect.t
  t/fips/ssls.t
  t/perf/conf/nginx.conf
  t/perf/requirements.txt
  t/perf/test_http.py
Labels: CI, size:XL

#11604 feat: add plugin attach-consmer-label
  apisix/cli/config.lua
  apisix/plugins/attach-consumer-label.lua
  conf/config.yaml.example
  docs/en/latest/config.json
  docs/en/latest/plugins/attach-consumer-label.md
  docs/zh/latest/config.json
  docs/zh/latest/plugins/attach-consumer-label.md
  t/admin/plugins.t
  t/plugin/attach-consumer-label.t
Labels: enhancement, plugin, doc, size:XL

#11597 feat: Jwt-auth plugin no longer requires a private_key to be uploaded.
  apisix/plugins/jwt-auth.lua
  docs/en/latest/plugin-develop.md
  docs/en/latest/plugins/jwt-auth.md
  docs/en/latest/plugins/public-api.md
  docs/zh/latest/plugin-develop.md
  docs/zh/latest/plugins/jwt-auth.md
  docs/zh/latest/plugins/public-api.md
  t/config-center-yaml/consumer.t
  t/lib/apisix/plugins/jwt-auth.lua
  t/plugin/jwt-auth.t
  t/plugin/jwt-auth2.t
  t/plugin/jwt-auth3.t
  t/plugin/jwt-auth4.t
  t/plugin/multi-auth.t
  t/plugin/plugin.t
  t/plugin/public-api.t
Labels: enhancement, plugin, doc, size:XXL

#11611 feat(splunk-logger): allow configuring keepalive_timeout
  apisix/plugins/splunk-hec-logging.lua
  docs/en/latest/plugins/splunk-hec-logging.md
  t/plugin/splunk-hec-logging.t
Labels: enhancement, plugin, size:M
