Repository apache/apisix, pull requests merged in 2024-02, with the labels that each got.

#10703 feat: add http-dubbo plugin
  .github/workflows/build.yml
  .github/workflows/centos7-ci.yml
  .github/workflows/gm-cron.yaml
  .github/workflows/redhat-ci.yaml
  .gitignore
  apisix/plugins/http-dubbo.lua
  conf/config-default.yaml
  t/admin/plugins.t
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-interface/pom.xml
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-interface/src/main/java/org/apache/dubbo/backend/DubboSerializationTestService.java
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-interface/src/main/java/org/apache/dubbo/backend/PoJo.java
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/pom.xml
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/src/main/java/org/apache/dubbo/backend/provider/DubboSerializationTestServiceImpl.java
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/src/main/java/org/apache/dubbo/backend/provider/Provider.java
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/src/main/resources/META-INF/spring/dubbo-demo-provider.xml
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/src/main/resources/dubbo.properties
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/src/main/resources/log4j.properties
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/target/classes/META-INF/spring/dubbo-demo-provider.xml
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/target/classes/dubbo.properties
  t/lib/dubbo-serialization-backend/dubbo-serialization-backend-provider/target/classes/log4j.properties
  t/lib/dubbo-serialization-backend/pom.xml
  t/plugin/http-dubbo.t
Labels: wait for update, user responded

#10905 feat(control): add plugins/reload to control api
  apisix/control/router.lua
  apisix/control/v1.lua
  apisix/init.lua
  docs/en/latest/control-api.md
  t/control/plugins-reload.t
Labels: wait for update, user responded

#10943 docs: update `opentelemetry` plugin doc attribute and correct otel collector misplaced comment in config file
  conf/config-default.yaml
  docs/en/latest/plugins/opentelemetry.md
  docs/zh/latest/plugins/opentelemetry.md
Labels: approved

#10902 fix: when delete the secret cause 500 error
  apisix/secret.lua
  t/secret/secret_lru.t
Labels: approved

#10917 fix: wrong namespace related endpoint in k8s
  apisix/discovery/kubernetes/informer_factory.lua
Labels: discuss, user responded

#10948 fix(cors): all origins could pass when allow_origins_by_metadata is set
  apisix/plugins/cors.lua
  t/plugin/cors3.t
Labels: approved

#10959 fix: add apisix/plugin/limit-req to makefile
  Makefile
Labels: wait for update, user responded

#10941 feat: consul deduplicate and ip port sort
  apisix/discovery/consul/init.lua
  apisix/discovery/consul/schema.lua
  ci/pod/docker-compose.first.yml
  docs/en/latest/discovery/consul.md
  t/discovery/consul2.t
Labels: need test cases, user responded
