Repository apache/apisix, pull requests merged in 2025-07, with the labels that each got.

#11889 docs: improve `openid-connect` plugin doc and add keycloak OIDC tutorial
  docs/en/latest/config.json
  docs/en/latest/plugins/openid-connect.md
  docs/en/latest/tutorials/keycloak-oidc.md
  docs/zh/latest/config.json
  docs/zh/latest/plugins/openid-connect.md
  docs/zh/latest/tutorials/keycloak-oidc.md
Labels: doc, size:XXL

#12413 fix(consumer): missed consumer update due to wrong version in cache
  apisix/consumer.lua
  t/admin/consumer-credentials.t
Labels: bug, size:L

#12403 fix: zipkin trace_id and span_id format in ngx_var
  apisix/plugins/zipkin.lua
  t/plugin/mcp-bridge.t
  t/plugin/zipkin3.t
Labels: bug, size:M

#12407 feat: add a global switch to disable upstream health check
  apisix/cli/schema.lua
  apisix/upstream.lua
  conf/config.yaml.example
  t/node/healthcheck-global-switch.t
Labels: enhancement, size:L

#12406 fix(request-validation): support Content-Type header with charset for urlencoded data
  apisix/plugins/request-validation.lua
  t/plugin/request-validation.t
Labels: bug, size:S

#12420 docs: add dashboard ui tips
  docs/en/latest/FAQ.md
  docs/en/latest/getting-started/README.md
  docs/zh/latest/FAQ.md
  docs/zh/latest/getting-started/README.md
Labels: doc, size:XS

#12411 fix(opentelemetry): remove plugin attr set_ngx_var
  apisix/cli/ngx_tpl.lua
  apisix/cli/ops.lua
  docs/en/latest/plugins/opentelemetry.md
  docs/zh/latest/plugins/opentelemetry.md
Labels: bug, plugin, size:M

#12434 docs: fix typo
  docs/en/latest/terminology/credential.md
Labels: doc, size:XS

#11824 feat: support OIDC claim validator (#8772)
  apisix/plugins/openid-connect.lua
  docs/en/latest/plugins/openid-connect.md
  docs/zh/latest/plugins/openid-connect.md
  t/plugin/openid-connect2.t
Labels: enhancement, size:L

#12383 feat: decoupled prometheus exporter's calculation and output
  apisix/cli/config.lua
  apisix/cli/ngx_tpl.lua
  apisix/core/config_etcd.lua
  apisix/init.lua
  apisix/plugin.lua
  apisix/plugins/prometheus.lua
  apisix/plugins/prometheus/exporter.lua
  apisix/stream/plugins/prometheus.lua
  conf/config.yaml.example
  t/APISIX.pm
  t/cli/test_prometheus.sh
  t/cli/test_prometheus_run_in_privileged.sh
  t/cli/test_prometheus_stream.sh
  t/plugin/prometheus.t
  t/plugin/prometheus2.t
  t/plugin/prometheus3.t
  t/plugin/prometheus4.t
Labels: enhancement, size:XL

#12462 fix: skipped failing bailedout tests in CI
  apisix/plugins/ai-drivers/openai-base.lua
  apisix/plugins/ai-request-rewrite.lua
  apisix/plugins/chaitin-waf.lua
  ci/common.sh
  ci/linux_openresty_common_runner.sh
  ci/redhat-ci.sh
  t/plugin/ai-proxy.openai-compatible.t
  t/plugin/ai-rate-limiting.t
  t/plugin/ai-request-rewrite2.t
  t/plugin/ai3.t
  t/plugin/chaitin-waf-reject.t
Labels: bug, CI, size:M

#12460 docs: update rpm installation guide
  docs/en/latest/installation-guide.md
  docs/zh/latest/installation-guide.md
Labels: doc, approved, size:S

#12450 docs: update `jwt-auth` docs
  docs/en/latest/plugins/jwt-auth.md
  docs/zh/latest/plugins/jwt-auth.md
Labels: doc, approved, size:XL

#11943 feat(datadog): Improve Datadog plugin tag support
  apisix/plugins/datadog.lua
  docs/en/latest/plugins/datadog.md
  t/plugin/datadog.t
Labels: enhancement, plugin, size:L

#12435 fix(forward-auth): extra_headers not resolving variable on $post_arg.
  apisix/core/utils.lua
  docs/en/latest/plugins/forward-auth.md
  docs/zh/latest/plugins/forward-auth.md
  t/plugin/forward-auth.t
Labels: bug, size:M

#12473 chore: upgrade deps to solve vulnerability alerts
  t/package.json
  t/pnpm-lock.yaml
Labels: dependencies, size:XS

#12474 fix: batch processor cache not working when configure plugin in service
  apisix/utils/batch-processor-manager.lua
  apisix/utils/batch-processor.lua
  t/plugin/kafka-logger.t
Labels: bug, size:M
