Repository apache/apisix, pull requests merged in 2025-05, with the labels that each got.

#12179 feat: add standalone admin api
  apisix/admin/init.lua
  apisix/admin/standalone.lua
  apisix/cli/config.lua
  apisix/cli/file.lua
  apisix/cli/ngx_tpl.lua
  apisix/cli/ops.lua
  apisix/cli/schema.lua
  apisix/core/config_yaml.lua
  ci/linux_openresty_common_runner.sh
  conf/config.yaml.example
  docs/en/latest/deployment-modes.md
  t/APISIX.pm
  t/admin/standalone.spec.ts
  t/admin/standalone.t
  t/discovery/consul_dump.t
  t/jest.config.ts
  t/package.json
  t/pnpm-lock.yaml
  t/tsconfig.json
Labels: enhancement, size:XL

#12180 feat: support health checker for stream subsystem
  apisix/cli/config.lua
  apisix/cli/ngx_tpl.lua
  apisix/init.lua
  apisix/upstream.lua
  conf/config.yaml.example
  t/APISIX.pm
  t/stream-node/healthcheck-resty-events.t
  t/stream-node/healthcheck-resty-worker-events.t
Labels: enhancement, size:XL

#12199 fix: `.asf.yaml` format
  .asf.yaml
Labels: bug, size:L

#12218 change: delete the `server-info` plugin
  apisix/cli/config.lua
  apisix/plugins/server-info.lua
  conf/config.yaml.example
  docs/en/latest/config.json
  docs/en/latest/plugins/server-info.md
  docs/zh/latest/config.json
  docs/zh/latest/plugins/server-info.md
  t/admin/plugins.t
  t/control/schema.t
  t/debug/debug-mode.t
  t/plugin/server-info.t
Labels: plugin, performance, size:XL

#12223 test: merge separately http3 cases
  .github/workflows/build.yml
  .github/workflows/http3.yml
  ci/common.sh
  ci/redhat-ci.sh
  t/APISIX.pm
Labels: github_actions, size:L

#12225 revert: "change: delete the `server-info` plugin"
  apisix/cli/config.lua
  apisix/plugins/server-info.lua
  conf/config.yaml.example
  docs/en/latest/config.json
  docs/en/latest/plugins/server-info.md
  docs/zh/latest/config.json
  docs/zh/latest/plugins/server-info.md
  t/admin/plugins.t
  t/control/schema.t
  t/debug/debug-mode.t
  t/plugin/server-info.t
Labels: plugin, size:XL

#12214 feat(standalone): support revision in API-driven standalone mode like etcd
  apisix/admin/standalone.lua
  apisix/core/config_yaml.lua
  docs/en/latest/deployment-modes.md
  t/admin/standalone.spec.ts
  t/admin/standalone.t
Labels: enhancement, size:XL

#12200 feat: add healthcheck for sync configuration
  apisix/cli/config.lua
  apisix/cli/ngx_tpl.lua
  apisix/cli/ops.lua
  apisix/core/config_etcd.lua
  apisix/core/config_yaml.lua
  apisix/init.lua
  conf/config.yaml.example
  docs/en/latest/config.json
  docs/en/latest/status-api.md
  docs/zh/latest/config.json
  docs/zh/latest/status-api.md
  t/APISIX.pm
  t/admin/standalone-healthcheck.t
  t/cli/test_status_api.sh
Labels: enhancement, size:XL

#12196 feat: add lago plugin
  apisix/cli/config.lua
  apisix/plugins/lago.lua
  conf/config.yaml.example
  docs/en/latest/config.json
  docs/en/latest/plugins/lago.md
  t/admin/plugins.t
  t/plugin/lago.spec.mts
  t/plugin/lago.t
Labels: enhancement, plugin, size:XL

#12216 fix: only parse and validate apisix.yaml in cli when startup
  apisix/cli/file.lua
Labels: bug, size:XS

#12258 perf: compare service discovery nodes by addresss
  apisix/upstream.lua
  apisix/utils/upstream.lua
Labels: size:M

#12224 feat: fill in the metadata of resource schema
  apisix/schema_def.lua
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
  t/admin/metadata.spec.ts
  t/admin/metadata.t
  t/ts/admin_api.ts
Labels: enhancement, size:L

#12256 fix(standalone): API-driven mode does not properly handle consumer schema
  apisix/admin/standalone.lua
  apisix/consumer.lua
  apisix/core/config_etcd.lua
  apisix/core/config_yaml.lua
  apisix/stream/router/ip_port.lua
  t/admin/standalone.spec.ts
  t/cli/test_status_api.sh
Labels: bug, size:L
