Repository apache/apisix, pull requests merged in 2025-09, with the labels that each got.

#12555 feat(ai-proxy): add upstream_response_time in access log
  apisix/cli/ngx_tpl.lua
  apisix/core/ctx.lua
  apisix/init.lua
  apisix/plugins/ai-drivers/openai-base.lua
  apisix/plugins/ai-proxy/base.lua
  t/APISIX.pm
  t/core/ctx4.t
  t/plugin/ai-proxy3.t
Labels: enhancement, size:L

#12571 feat: add fallback mechanism for specific error codes in ai-proxy-multi
  apisix/plugins/ai-drivers/openai-base.lua
  apisix/plugins/ai-proxy-multi.lua
  apisix/plugins/ai-proxy/base.lua
  apisix/plugins/ai-proxy/schema.lua
  apisix/plugins/ai-request-rewrite.lua
  docs/en/latest/plugins/ai-proxy-multi.md
  docs/en/latest/plugins/ai-rate-limiting.md
  t/plugin/ai-proxy-multi.balancer.t
Labels: enhancement, size:XL

#12584 fix(ai-proxy-multi): panic when instance dont have custom endpoint
  apisix/plugins/ai-proxy-multi.lua
  t/plugin/ai-proxy-multi3.t
Labels: bug, size:M

#12573 feat: add ksuid algorithm on request-id plugin
  apisix-master-0.rockspec
  apisix/plugins/request-id.lua
  docs/en/latest/plugins/request-id.md
  docs/zh/latest/plugins/request-id.md
  t/plugin/request-id3.t
Labels: enhancement, size:L

#12587 fix: correct spelling error in get_healthcheck_events_module function name
  apisix/events.lua
  apisix/healthcheck_manager.lua
Labels: bug, size:XS

#12608 docs: Improve `chaitin-waf` plugin docs and remove unintended highlights
  docs/en/latest/plugins/attach-consumer-label.md
  docs/en/latest/plugins/chaitin-waf.md
  docs/en/latest/plugins/jwt-auth.md
  docs/en/latest/plugins/proxy-rewrite.md
  docs/zh/latest/plugins/attach-consumer-label.md
  docs/zh/latest/plugins/chaitin-waf.md
  docs/zh/latest/plugins/jwt-auth.md
  docs/zh/latest/plugins/proxy-rewrite.md
Labels: doc, size:XL

#12612 docs: update notes for API-drive standalone mode
  docs/en/latest/deployment-modes.md
Labels: doc, size:XS

#12616 docs: add new dashboard documentation
  docs/assets/images/dashboard-admin-key-is-correct.png
  docs/assets/images/dashboard-admin-key-is-wrong.png
  docs/assets/images/dashboard-need-admin-key.png
  docs/assets/images/dashboard-reopen-settings-modal.png
  docs/assets/images/dashboard-settings-btn-icon.png
  docs/assets/images/dashboard.jpeg
  docs/en/latest/config.json
  docs/en/latest/dashboard.md
  docs/en/latest/getting-started/README.md
  docs/zh/latest/config.json
  docs/zh/latest/dashboard.md
  docs/zh/latest/getting-started/README.md
Labels: doc, size:L

#12614 fix(secret): refresh stale lru cache item in background
  apisix/cli/config.lua
  apisix/core/lrucache.lua
  apisix/init.lua
  apisix/secret.lua
  conf/config.yaml.example
  t/core/lrucache.t
  t/router/radixtree-sni2.t
Labels: bug, size:L

#12566 fix: embedded UI redirect error when behind proxy
  apisix/cli/ngx_tpl.lua
  t/cli/test_admin_ui.sh
Labels: bug, size:S

#12603 feat: admin api no longer populates default values when writing
  apisix/admin/consumer_group.lua
  apisix/admin/consumers.lua
  apisix/admin/credentials.lua
  apisix/admin/global_rules.lua
  apisix/admin/plugin_config.lua
  apisix/admin/plugin_metadata.lua
  apisix/admin/plugins.lua
  apisix/admin/resource.lua
  apisix/admin/routes.lua
  apisix/admin/services.lua
  apisix/admin/upstreams.lua
  apisix/admin/utils.lua
  apisix/plugins/request-id.lua
  apisix/upstream.lua
  t/admin/consumer-group.t
  t/admin/global-rules.t
  t/admin/global-rules2.t
  t/admin/plugin-configs.t
  t/admin/routes2.t
  t/admin/routes4.t
  t/admin/services.t
  t/admin/services2.t
  t/admin/ssl2.t
  t/admin/stream-routes.t
  t/admin/upstream.t
  t/admin/upstream2.t
  t/plugin/jwt-auth.t
  t/plugin/proxy-rewrite.t
  t/plugin/request-id2.t
  t/plugin/response-rewrite.t
Labels: enhancement, size:L

#12561 fix(plugin/redirect): ensure redirect when scheme is not `https`
  apisix/plugins/redirect.lua
  t/plugin/redirect.t
Labels: bug, size:S

#12621 docs: update admin api documentation for plugin metadata list endpoint
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
Labels: doc, size:XS

#12594 fix(ai-proxy-multi): inconsistent resolved nodes for healthcheck
  apisix/plugins/ai-proxy-multi.lua
  t/plugin/ai-proxy-multi3.t
Labels: bug, size:L

#12632 fix: run init_worker of apisix.admin module in stream subsystem
  apisix/init.lua
  t/admin/standalone.t
Labels: bug, size:M
