Repository apache/apisix, pull requests merged in 2025-08, with the labels that each got.

#12465 feat: support limit-conn in workflow plugin
  apisix/plugins/limit-conn.lua
  apisix/plugins/limit-count.lua
  apisix/plugins/workflow.lua
  docs/en/latest/plugins/workflow.md
  docs/zh/latest/plugins/workflow.md
  t/plugin/workflow3.t
Labels: enhancement, size:L

#12503 docs: remove LLM variable in access log examples
  docs/en/latest/plugins/ai-proxy-multi.md
  docs/en/latest/plugins/ai-proxy.md
Labels: doc, size:L

#12518 feat(ai-proxy): add latency and usage in access log and prometheus metrics
  apisix/cli/ngx_tpl.lua
  apisix/core/ctx.lua
  apisix/plugins/ai-drivers/openai-base.lua
  apisix/plugins/ai-proxy-multi.lua
  apisix/plugins/ai-proxy.lua
  apisix/plugins/ai-proxy/base.lua
  apisix/plugins/ai-request-rewrite.lua
  apisix/plugins/prometheus/exporter.lua
  conf/config.yaml.example
  docs/en/latest/plugins/ai-proxy-multi.md
  docs/en/latest/plugins/ai-proxy.md
  docs/en/latest/plugins/prometheus.md
  docs/zh/latest/plugins/prometheus.md
  t/APISIX.pm
  t/plugin/ai-proxy-multi.balancer.t
  t/plugin/ai-proxy-multi.openai-compatible.t
  t/plugin/ai-proxy-multi.t
  t/plugin/ai-proxy-multi2.t
  t/plugin/ai-proxy3.t
  t/plugin/ai-rate-limiting.t
  t/plugin/prometheus-ai-proxy.t
  t/plugin/prometheus.t
  t/plugin/prometheus2.t
  t/plugin/prometheus3.t
  t/plugin/prometheus4.t
Labels: enhancement, size:XXL

#12523 fix(etcd): load full data from etcd while worker restart
  apisix/cli/config.lua
  apisix/core/config_etcd.lua
  conf/config.yaml.example
  t/cli/test_load_full_data_init_worker.sh
Labels: bug, size:L

#12527 fix: when only `tls.verify`, skip the logic of judging client cert
  apisix/upstream.lua
  docs/en/latest/admin-api.md
  docs/zh/latest/admin-api.md
  t/core/schema_def.t
  t/node/upstream-mtls.t
Labels: bug, size:L

#11451 feat: allow to use environment variables for openid-connect plugin
  apisix/plugins/openid-connect.lua
  docs/en/latest/plugins/openid-connect.md
  docs/zh/latest/plugins/openid-connect.md
  t/plugin/openid-connect.t
  t/plugin/openid-connect9.t
Labels: size:L

#12539 fix: basic auth scheme supports case insensitivity
  apisix/plugins/basic-auth.lua
  apisix/plugins/ldap-auth.lua
  t/plugin/basic-auth.t
  t/plugin/ldap-auth.t
Labels: bug, size:L

#12536 fix(discovery/kubernetes): adjust id length
  apisix/discovery/kubernetes/schema.lua
  t/discovery/kubernetes_schema.t
Labels: bug, size:M

#12548 fix(ai-proxy): check type of choices/usage/content fields before use it
  apisix/plugins/ai-drivers/openai-base.lua
  t/plugin/ai-proxy3.t
Labels: bug, size:M

#12564 fix: missing ctx.llm_raw_usage in non-stream mode
  apisix/plugins/ai-drivers/openai-base.lua
Labels: bug, size:XS

#12565 feat: add support for azure-ai driver
  apisix/plugins/ai-drivers/azure-openai.lua
  apisix/plugins/ai-drivers/openai-base.lua
  apisix/plugins/ai-proxy/schema.lua
  docs/en/latest/plugins/ai-proxy-multi.md
  docs/en/latest/plugins/ai-proxy.md
  docs/en/latest/plugins/ai-request-rewrite.md
  t/plugin/ai-proxy-azure-openai.t
Labels: enhancement, size:L

#12563 fix(ai-proxy): catch malformed override endpoint in schema validation
  apisix/plugins/ai-proxy-multi.lua
  t/plugin/ai-proxy-multi.t
Labels: bug, size:M
