Repository apache/apisix, pull requests merged in 2025-06, with the labels that each got.

#11765 feat: support devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
  .devcontainer/docker-compose.yml
  .gitignore
  docs/assets/images/build-devcontainers-vscode-command.png
  docs/assets/images/build-devcontainers-vscode-progressbar.png
  docs/en/latest/build-apisix-dev-environment-devcontainers.md
  docs/en/latest/config.json
Labels: enhancement, size:L

#12277 fix: temporary fix for broken luarocks server
  .github/workflows/code-lint.yml
  Makefile
  autodocs/generate.sh
  ci/common.sh
  ci/linux_apisix_current_luarocks_runner.sh
Labels: bug, size:S

#12243 feat: add `headers` attribute for `loki-logger` (#11420)
  apisix/plugins/loki-logger.lua
  docs/en/latest/plugins/loki-logger.md
  docs/zh/latest/plugins/loki-logger.md
  t/plugin/loki-logger.t
Labels: enhancement, size:M

#12168 refactor: mcp server framework implementation
  Makefile
  apisix/plugins/mcp-bridge.lua
  apisix/plugins/mcp/broker/shared_dict.lua
  apisix/plugins/mcp/broker/utils.lua
  apisix/plugins/mcp/server.lua
  apisix/plugins/mcp/server_wrapper.lua
  apisix/plugins/mcp/session.lua
  apisix/plugins/mcp/transport/sse.lua
  t/plugin/mcp-bridge.t
Labels: enhancement, size:XL

#12244 change: mark `server-info` plugin as deprecated
  apisix/cli/config.lua
  apisix/plugins/server-info.lua
  conf/config.yaml.example
  docs/en/latest/plugins/server-info.md
  docs/zh/latest/plugins/server-info.md
  t/admin/plugins.t
  t/debug/debug-mode.t
Labels: plugin, doc, size:S

#12295 feat(standalone): allow more characters in credential_id for API-driven mode
  apisix/admin/standalone.lua
  t/admin/standalone.spec.ts
Labels: enhancement, size:XS

#12299 fix: original key being modified causing cache inconsistency
  apisix/core/ctx.lua
  t/core/ctx3.t
Labels: bug, size:L

#12305 chore: upgrade luarocks version
  utils/linux-install-luarocks.sh
Labels: chore, size:XS

#12306 revert: temporary fix regarding luarocks
  .github/workflows/code-lint.yml
  Makefile
  autodocs/generate.sh
  ci/common.sh
  ci/linux_apisix_current_luarocks_runner.sh
Labels: size:S

#12308 docs: update CHANGELOG with recent changes
  CHANGELOG.md
Labels: chore, size:S

#12300 feat(workflow): push `apisix:dev` image on commit
  .github/workflows/push-dev-image-on-commit.yml
  Makefile
  docker/compose/apisix_conf/master/config.yaml
  docker/compose/docker-compose-master.yaml
  docker/debian-dev/Dockerfile
  docker/debian-dev/docker-entrypoint.sh
  docker/debian-dev/install-brotli.sh
  docker/utils/check_standalone_config.sh
Labels: enhancement, github_actions, size:L

#12317 fix: check if `config` contains duplicate resources in API-driven standalone mode
  apisix/admin/standalone.lua
  t/admin/standalone.t
Labels: bug, size:M

#12304 fix: handle consul nil port cases by defaulting to port 80
  apisix/discovery/consul/init.lua
  docs/en/latest/discovery/consul.md
  t/discovery/consul2.t
Labels: bug, size:M

#12347 ci: add GitHub Action to check CHANGELOG consistency with PRs
  .github/workflows/check-changelog.yml
  ci/check_changelog_prs.ts
Labels: github_actions, size:L

#12338 feat: add max pending entries option to batch-processor
  apisix/plugins/kafka-logger.lua
  apisix/utils/batch-processor-manager.lua
  apisix/utils/batch-processor.lua
  t/plugin/kafka-logger3.t
Labels: enhancement, size:L

#12370 fix: flaky t/admin/filter.t due to url encoding for query params
  t/admin/filter.t
Labels: bug, size:XS

#12369 feat: add apisix dashboard to dev image
  .github/workflows/push-dev-image-on-commit.yml
  docker/debian-dev/Dockerfile
Labels: enhancement, size:S

#12361 refactor: change log level to debug to avoid unnecessary logs
  apisix/core/ctx.lua
  t/core/ctx3.t
Labels: chore, size:XS

#12367 feat: expose apisix version in prometheus node info metric
  apisix/plugins/prometheus/exporter.lua
  docs/en/latest/plugins/prometheus.md
  docs/zh/latest/plugins/prometheus.md
  t/plugin/prometheus4.t
Labels: enhancement, size:S

#12353 feat: replace events library with shdict
  apisix/cli/ngx_tpl.lua
  apisix/discovery/nacos/init.lua
  t/APISIX.pm
  t/discovery/nacos.t
  t/discovery/nacos2.t
Labels: enhancement, size:L

#12382 ci: remove redundant package steps
  .github/workflows/build.yml
Labels: github_actions, size:S

#12375 fix: deployment data plane with read-only etcd
  apisix/cli/etcd.lua
  t/cli/test_deployment_data_plane_with_readonly_etcd.sh
Labels: bug, size:L

#12364 fix: support multiple versions of Elasticsearch logger
  apisix/plugins/elasticsearch-logger.lua
  ci/pod/docker-compose.plugin.yml
  docs/en/latest/plugins/elasticsearch-logger.md
  docs/zh/latest/plugins/elasticsearch-logger.md
  t/plugin/elasticsearch-logger.t
Labels: bug, enhancement, plugin, size:L

#12378 chore: release 3.13.0
  .asf.yaml
  CHANGELOG.md
  apisix/core/version.lua
  ci/check_changelog_prs.ts
  docs/en/latest/building-apisix.md
  docs/en/latest/config.json
  docs/zh/latest/building-apisix.md
  docs/zh/latest/config.json
Labels: chore, size:M
